infra:
  namespace: helm-template
  airflow:
    image: docker.io/sankethacr/dss-airflow-image:v28
    replicas: 1

  postgres:
    image: postgres:9.6.14
    replicas: 1

  services:
    ingress:
        enabled: true
    airflow:
        enabled: true
    postgres:
        enabled: true

application:
  namespace: helm-template
  airflowWrapper: 
    image: 10.113.56.67/ngp-develop/dss-airflow-service-service:20210204121655
    name: dss-airflow-wrapper
    replicas: 1

  dssClintApplication:
    image: 10.113.56.67/ngp-develop/data-science-studio-ui:20210324194515
    replicas: 1
  dssServiceApplication:
    image: 10.113.56.67/ngp-develop/data-science-studio-service:20210325145819
    replicas: 1
  
  services:
    airflowWrapperIngress:
        enabled: true
    airflowWrapperService:
        enabled: true

    dssClientService:
        enabled: true
    dssClientIngress:
        enabled: true

    dssServiceService:
        enabled: true
    dssServiceIngress:
        enabled: true
    