infra:
  namespace: helm-template
  airflow:
    image: docker.io/subexdss/dss-airflow-image:v3
    replicas: 1
    ports:
      nodePort: 30222

  postgres:
    image: postgres:9.6.14
    replicas: 1

  services:
    ingress:
        enabled: true
    airflow:
        enabled: true
    postgres:
        enabled: true

application:
  namespace: helm-template
  airflowWrapper: 
    image: docker.io/subexdss/dss-airflow-wrapper:v3
    name: dss-airflow-wrapper
    replicas: 1
    ports:
      nodePort: 30333

  dssClintApplication:
    image: docker.io/subexdss/data-science-studio-ui:v1
    replicas: 1
    ports: 
      nodePort: 30111
  dssServiceApplication:
    image: docker.io/subexdss/data-science-studio-service:v1
    replicas: 1
  
  services:
    airflowWrapperIngress:
        enabled: true
    airflowWrapperService:
        enabled: true

    dssClientService:
        enabled: true
    dssClientIngress:
        enabled: true

    dssServiceService:
        enabled: true
    dssServiceIngress:
        enabled: true
    