{{- if .Values.services.airflowWrapperService.enabled -}}
apiVersion: v1
data:
  application.properties: |-
    ################################ Spring Default Properties ##################################

    spring.application.name=dss-airflow-service
    springfox.documentation.swagger.v2.path=/api-docs
    server.contextPath=/
    server.port=8080
    spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
    spring.jpa.show-sql=false
    spring.datasource.hikari.connectionTimeout=20000
    spring.datasource.hikari.maximumPoolSize=5
    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
    spring.jpa.properties.hibernate.format_sql=false
    ###########################################################################################



    ################################ Database Properties ######################################

    spring.datasource.url=jdbc:postgresql://ngp-postgres:5432/dssairflowservice
    spring.datasource.username=dssairflowservice
    spring.datasource.password=dssairflowservice
    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
    ###########################################################################################

    ############################### oracle Properties ############################
   
    spring.oracle.url=
    spring.oracle.username=
    spring.oracle.password=


    ################################ Flyway Properties ########################################

    spring.flyway.locations=classpath:/flyway/migration
    spring.flyway.url=jdbc:postgresql://ngp-postgres:5432/dssairflowservice
    spring.flyway.schemas=public
    spring.flyway.user=dssairflowservice
    spring.flyway.password=dssairflowservice
    spring.flyway.baselineVersion=0.0.1
    spring.flyway.baselineOnMigrate=false
    spring.flyway.enabled=true
    spring.flyway.runFlyWay.afterJPA=true
    ##########################################################################################


    ################################ Keycloak Properties ########################################

    keycloak.realm=sys-testing
    keycloak.resource=dss-airflow-service
    keycloak.auth-server-url=http://10.113.104.24:31353/auth
    keycloak.ssl-required=external
    keycloak.public-client=true
    keycloak.bearer-only=true
    keycloak.principal-attribute=preferred_username
    keycloak.cors=true
    keycloak.use-resource-role-mappings=true

    ##########################################################################################

    ngp.register_server.token_uri=http://ngp-keycloak:8080/auth/realms/sys-testing/protocol/openid-connect/token
    ngp.register_server.client_id=common-services-apiservice
    ngp.common-services.apiservice.url=http://ngp-common-services-service:8080


    ################################ NGP Application Registration Properties ###############################

    ngp.register.enabled=true
    ngp.register.service.id=dss-airflow-service
    ngp.register.service.name=Dss Airflow Service Service
    ngp.register.service.url=http://10.113.104.24:30109/
    ngp.register.service.description=Dss Airflow Service
    ngp.register.service.create.default.users=true

    ngp.register.apiservice.enabled=false
    ngp.register.apiservice.id=dss-airflow-service-apiservice
    ngp.register.apiservice.name=Dss Airflow Service API Service
    ngp.register.apiservice.description=Dss Airflow Service API Service
    ngp.register.apiservice.roles=configuration_view

    ngp.register.force.delete=false
    
    ngp.security.enabled=false
    server.servlet.context-path=/dss-airflow-service
    
    ngp.airflow.apiservice.url=http://10.113.113.95:8080/api/experimental/
    ngp.airflow.template.path=src/main/resources/template
    ngp.airflow.dag.path=src/main/resources/dagfiles

    ###############################Logproperties##################################################

    logging.pattern.console= %clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){yellow} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} [%F] [%M] [%C]:%L %clr(---){faint} %clr([%t]){faint} ${hostName} %clr(%logger{39}){cyan} %clr(:){faint} %m %throwable{short.className} %X{correlationId} %X{userId} %X{sessionId} %X{serviceName} %n%n


kind: ConfigMap
metadata:
  name: dss-airflow-service-application-properties 
{{- end -}}