{{- if .Values.services.airflowWrapperService.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.airflowWrapper.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.airflowWrapper.name }}
spec:
  replicas: {{ .Values.airflowWrapper.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.airflowWrapper.name }}
  template:
    metadata:      
      labels:
        app: {{ .Values.airflowWrapper.name }}
    spec:
      containers:
        - name: {{ .Values.airflowWrapper.name }}
          image: {{ .Values.airflowWrapper.image }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.airflowWrapper.ports.containerPort }}
              name: {{ .Values.airflowWrapper.ports.name }}
          volumeMounts:
            - name: {{ .Values.airflowWrapper.volumeMounts.configVolume }}
              mountPath: {{ .Values.airflowWrapper.volumeMounts.configMountPath }}
            - name: {{ .Values.airflowWrapper.volumeMounts.sharedVolume }}
              mountPath: {{ .Values.airflowWrapper.volumeMounts.sharedMountPath }} 
            - mountPath: "/usr/local/airflow/logs"
              name: logs-volume
            - mountPath: "/usr/local/airflow/dags"
              name: dags-volume
            - mountPath: "/usr/local/airflow/data"
              name: data-volume
            - mountPath: "/usr/local/airflow/modelrepository"
              name: modelrepository-volume 
            - mountPath: "/usr/local/airflow/output"
              name: output-volume
              
      volumes:
        - name: {{ .Values.airflowWrapper.volumeMounts.configVolume }}
          configMap:
            name: {{ .Values.airflowWrapper.volumes.configProperties }}
        - name: {{ .Values.airflowWrapper.volumeMounts.sharedVolume }}
          persistentVolumeClaim:
            claimName: {{ .Values.airflowWrapper.volumes.claimName }}
        - name: dags-volume
          persistentVolumeClaim:
            claimName: dags-pvc
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-pvc
        - name: modelrepository-volume
          persistentVolumeClaim:
            claimName: modelrepository-pvc
        - name: output-volume
          persistentVolumeClaim:
            claimName: output-pvc
{{- end -}}