kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config-pvc
  namespace: {{ .Values.namespae }}
  labels:
    app: ngp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: script-pvc
  namespace: {{ .Values.namespae }}
  labels:
    app: ngp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pv-claim
  namespace: {{ .Values.namespae }}
  labels:
    app: ngp
spec:
  storageClassName: nfs-provisioner
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dags-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: ngp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logs-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: ngp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: output-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: ngp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: ngp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: modelrepository-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: ngp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dask-data-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: ngp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: ngp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi