apiVersion: v1
kind: PersistentVolumeClaim        # Create a PersistentVolumeClaim to request a PersistentVolume storage
metadata:                          # Claim name and labels
  name: uploads-pv-claim
  namespace: {{ .Values.namespace }}
  labels:
    app: data-science-studio-service
spec:                              # Access mode and resource limits
  accessModes:
    - ReadWriteMany                # ReadWriteMany means the volume can be mounted as read-write by many Nodes
  resources:
    requests:
      storage: 1Gi