########################### Common service ########################################
namespace: helm-template
volume:
  shared:
    claimName: shared-pvc 
    sizeInGi: 1
########################### Airflow wrapper ########################################
airflowWrapper:
  name: dss-airflow-service-service
  image: docker.io/subexdss/dss-airflow-wrapper:v1
  ports:
    containerPort: 8080
    name: http
    nodePort: 30333
  volumeMounts:
    dssConfig: 
      claimName: dss-airflow-service-application-properties
      path: /deployments/config
    dssShared:
      claimName: shared-pv-claim
      path: /root/.ngp
    dssLogs:
      claimName: logs-pvc
      path: /usr/local/airflow/logs
    dssDags:
      claimName: dags-pvc
      path: /usr/local/airflow/dags
    dssData:
      claimName: data-pvc
      path: /usr/local/airflow/data
    dssOutput:
      claimName: output-pvc
      path: /usr/local/airflow/output
    dssModelrepository:
      claimName: modelrepository-pvc
      path: /usr/local/airflow/modelrepository

  environment:
    servicePrecondition: "ngp-postgres:5432"

  ingress:
    name: dss-airflow-service-ingress
    path: dss-airflow-service
############################ DSS UI (Client) service ########################################
dssClintApplication:
  name: data-science-studio-app-client
  image: docker.io/subexdss/data-science-studio-ui:v1
  replicas: 1
  ports:
    port: 80
    nodePort: 30111
    name: http
  volumeMounts:
    name: config-volume
    mountPath: /usr/share/nginx/html/assets/conf/api.config.json
    subPath: api.config.json
  volumes:
    configMapName: data-science-studio-api-config-v2

  ingress:
    name: dss-ui-ingress
    path: data-science-studio-ui

############################ DSS middle layer (service) #####################################
dssServiceApplication:
  name: data-science-studio-app-service
  image: docker.io/subexdss/data-science-studio-service:v1
  replicas: 1
  ports:
    port: 8080
    name: http
  volumeMounts:
    configName: config-volume
    configMountPath:  /deployments/config
    sharedName: shared-volume
    sharedMountPath: /root/.ngp
    uploadName: upload-volume
    uploadMountPath: /upload
  environment:
    servicePrecondition: "ngp-postgres:5432"
  volumes:
    configMapName: data-science-studio-application-properties-v1
    sharedClaimName: shared-pv-claim
    uploadClaimName: uploads-pv-claim

  ingress:
    name: data-science-studio-app-service-ingress
    path: dss-app-service

############################ Enable/Disable application services ##############################
services:
  airflowWrapperIngress:
      enabled: true
  airflowWrapperService:
      enabled: true

  dssClientService:
      enabled: true
  dssClientIngress:
      enabled: true

  dssServiceService:
      enabled: true
  dssServiceIngress:
      enabled: true