apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.airflow.name }}
  labels:
    app: {{ .Values.airflow.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.airflow.ports.airflowPort }}
      name: {{ .Values.airflow.ports.name }}
  selector:
   app: {{ .Values.airflow.name }}



