{{- if .Values.services.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: {{ .Values.ingress.name }}
    namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.airflow.name }}
          servicePort:  {{ .Values.airflow.ports.airflowPort }}
{{- end -}}

